### ISSUE TITLE
Game fails to load files from custom game vpk sometimes, causing missing elements

### ISSUE THREAD

**Issue by DoctorGester** [ModDota/BugTracker#1]
This is not reproducible in a good way, happens at random, but fairly often.
The crash is usually due to a missing modifier/ability file error (for lua abilities) and is only a symptom. When this happens you can see that all the panorama/content files have failed to load in the console.

**Comment by darklordabc** [comment]
> ### Wrong way
> ```lua
> if modifier_npc_dota_hero_alchemist_perk == nil then modifier_npc_dota_hero_alchemist_perk = class({}) end
> ```
> 
> It causes crash for unknown reason. Maybe because we are trying to modify already linked modifier and then link it once again.
> ### Correct way
> ```lua
> modifier_npc_dota_hero_alchemist_perk = class({})
> ```

**Comment by DoctorGester** [comment]
That's absolutely not it, the game just refuses to load any file from the game vpk, including panorama files.

**Comment by DoctorGester** [comment]
Happened multiple times after returning to dashboard and back to the game, resources just stop loading from the game VPK and eventually the game crashes

![img](http://dg-lab.com/mabuc)

**Comment by DoctorGester** [comment]
Does not crash anymore which is good, the issue still stands though because any new layout elements won't load, icons won't load, clientside modifiers won't load.

**Comment by DoctorGester** [comment]
Fixed in the https://steamdb.info/patchnotes/2529688/
