### ISSUE TITLE
DOTAScenePanel render model is particularly ugly

### ISSUE THREAD

**Issue by robincodex** [ModDota/BugTracker#111]
This is normal in tools mode, but I submit to workshop this render model is particularly ugly.

![image](https://cloud.githubusercontent.com/assets/8408783/24375353/86ed4cf6-136a-11e7-908a-40317ad7bcc2.png)

**Comment by DoctorGester** [comment]
particleonly="false" on the scenepanel solves it, not a bug

Example
```<DOTAScenePanel id='QuestPointsScene' map='maps/scenes/battlepass_ti6_rewardintro.vmap' particleonly='false'/>```

**Comment by RobinCodeX** [comment]
Thank you very muck, you reply so quickly

**Comment by robincodex** [comment]
@DoctorGester Thank you very muck, you reply so quickly

**Comment by robincodex** [comment]
@DoctorGester  Do you know how to use skybox in background map?

**Comment by DoctorGester** [comment]
No
