### ISSUE TITLE
Implement panel-wise hotkeys

### ISSUE THREAD

**Issue by Arhowk** [ModDota/BugTracker#115]
Panel wise hotkeys are already implemented for things such as text boxes, the shop's grid hotkey search, and most recently the 1/2 hotkeys on the talent tree, but we don't have access to panel side hotkeys in JS panorama in order to replicate these features purely in panorama. (This is most needed to create a full feature recreation of talent tree, since the current system is very locked and inhibitive)

**Comment by DoctorGester** [comment]
Doesn't $.RegisterKeyBind use a parent panel as an argument?

**Comment by Arhowk** [comment]
Woops, it was broken when I tried it originally but the documentation in libpanorama showed I was messing it up. My bad.
