### ISSUE TITLE
Lua: Add IsDebuff() to CDOTA_Buff

### ISSUE THREAD

**Issue by robincodex** [ModDota/BugTracker#122]
if the modifier is from datadriven (or dota's buff), then it does not have this IsDebuff(), same as IsHidden() and IsPurgable().

**Comment by SinZ163** [comment]
Exists in [API dumps](https://github.com/SinZ163/TestTracking/commit/2fb64b6d2be06c6a8073355e8286baaefb4ce4e6) as of Build 3707 (Aug 13 2019)
