### ISSUE TITLE
Custom Game Item builds are now always hidden

### ISSUE THREAD

**Issue by Yahnich** [ModDota/BugTracker#126]
You can no longer place item build .txts in the itembuilds folder and have it show the player a suggested build, making entry into less dota-like games with more custom items in their shops harder.

**Comment by DoctorGester** [comment]
I think the workaround was to traverse the shop panel up and manually unhide the suggested items panel.

**Comment by DoctorGester** [comment]
```js
var dotaHud = $.GetContextPanel().GetParent().GetParent().GetParent().GetParent().GetParent().GetParent()
var shop = dotaHud.FindChildTraverse("shop")    
shop.RemoveClass("GuidesDisabled")
```

workaround by K1dney

**Comment by Yunten** [comment]
Or add "HeroGuidesSupported" "1" in addoninfo.txt

**Comment by Yahnich** [comment]
not a bug then i guess, they just changed how to activate them without telling us again
