### ISSUE TITLE
Implement a more verbose panorama API generator

### ISSUE THREAD

**Issue by Arhowk** [ModDota/BugTracker#128]
The current panorama API generator, quite frankly, is complete garbage. Run it against slitbreaker and it doesn't find a billion things like SetCameraTerrainHeightAdjustmentEnabled or CreateCustomKeyBinds or pane properties like actualuiscale_x, any properties of scenepanels like unitname, environment, etc. the list goes on and on.

**Comment by DoctorGester** [comment]
Are you sure it actually prints out any dota related functions right now. cl_panorama_script_help2 has been broken for a while and didn't show Entities/Game/Abilities etc. Furthermore it never displayed Buffs.

**Comment by Arhowk** [comment]
I wouldn't doubt if it didn't, I haven't referenced the JS API in a while I just use my own code for reference at this point.
