### ISSUE TITLE
heroselection.txt no longer removes heroes from hero selection

### ISSUE THREAD

**Issue by Yahnich** [ModDota/BugTracker#136]
they are still unselectable, but for gamemodes with only 14-ish available heroes it becomes annoying to find available heroes

**Comment by Arhowk** [comment]
you can enable inside the Hero definition using the "Enabled" key, but before that it checks the file activelist.txt

here is a step by step to fix the issue:

1. Open herolist.txt
2. Replace the "CustomHeroList" master key with "whitelist"
3. Rename herolist.txt to activelist.txt
there is still the issue of wrong abilities showing up in the Hero pick screen, just figuring that out now

**Comment by robincodex** [comment]
Now there need to exist more than 10 heroes.

My solution:
![image](https://user-images.githubusercontent.com/8408783/32457068-a8a6c162-c362-11e7-810d-e6117765afae.png)

**Comment by DoctorGester** [comment]
Can someone confirm that works again?
