### ISSUE TITLE
Suggestions to Improve "Open Lobbies" Widget

### ISSUE THREAD

**Issue by savecustomgames** [ModDota/BugTracker#143]
I'm talking about [this widget](https://imgur.com/5yQy17i) on the custom games tab. 
The first problem with this window is that it often doesn't work as presented. When you click the play button, you expect to join a currently open lobby with existing players in them, but very often, it puts you in an [empty lobby](https://imgur.com/Fvwkfyy) by yourself. 
It does this because the game does not want you to join a lobby that has poor ping. The lobby exists, but its not in your region. The game is advertising lobbies to you that it won't let you join. This is the problem. Whats worst is that even if there is an open lobby in your region with good ping, the open lobby widget does not prioritize that at the top or give any indication. So for an Australian at 12am, this open lobby list is useless, because even if there is a custom game being hosted by an Australian, its impossible to tell it apart from all the other lobbies. I don't think Valve intended this, and it makes it hard for smaller custom games to find players. 

Which gets me to the first suggestion.

a) Filter out lobbies, so that it only shows lobbies that it will let you join, i.e. the lobbies in your region. 

or

b) [Change](https://imgur.com/VDp9tz9) the "Play" button to "Join Lobby" or "Create Lobby" so that its clear which games will result in joining other players. Also, place the "Join" lobbies above the rest.  

another solution is 
 
c) Allow players to join the lobbies even if they result in joining a lobby with poor ping. With this option, it should [show](https://imgur.com/imWZRqU) the ping of servers and order them by ping. (I personally prefer this option most)

In all cases it should rank the lobbies by ping, that's very important, but after that, it should show the oldest lobbies first.

I think this is a pretty simple change that could really help less popular custom games be able to gather players and launch.

**Comment by darklordabc** [comment]
This should be closed it's was fixed with the lobby rework a while ago.
