### ISSUE TITLE
Dire lane creeps/tower ignoring radiant creeps, heroes and towers

### ISSUE THREAD

**Issue by rodlorric** [ModDota/BugTracker#145]
Hi, I'm the developer of the mod "[Last Hit Challenge](https://steamcommunity.com/sharedfiles/filedetails/?id=521345312)".

Since one of the recent updates, for some mysterious reason, as stated in the title, the dire creeps just run past the radiant creeps and do nothing when they arrive to the final path corner.

Obviously nothing has changed in my source code as it was working as intended prior that update (I don't know exactly which one, probably the one that broke other mods too).

Any clues about this?. I'm getting bombed by the subscribers of my mod asking for a fix to this bug, and I don't really know how to or even if it is something that I could possibly fix.

**Comment by Perryvw** [comment]
Remove TeamCount from addoninfo.txt

**Comment by rodlorric** [comment]
@Perryvw very big thank you!, that fixed it!.
Callout to Valve for breaking things almost with every update.
