### ISSUE TITLE
Allow SetCameraDistanceOverride to apply to individual players

### ISSUE THREAD

**Issue by darklordabc** [ModDota/BugTracker#18]
**Problem:** SetCameraDistanceOverride only affects all players, it can not be used to affect individual players

**Solution:** Allow passing to SetCameraDistanceOverride a player variable so we can affect it to individuals. 

**Priority:** Low

**Comment by darklordabc** [comment]
@DoctorGester please post the solution, just like the function name and I'll shut this issue.

**Comment by DoctorGester** [comment]
GameUI.SetCameraDistance( float flDistance )	
GameUI.SetCameraLookAtPositionHeightOffset( float flCameraLookAtHeightOffset )
