### ISSUE TITLE
Radar button can not be hidden by hiding any default UI types

### ISSUE THREAD

**Issue by DoctorGester** [ModDota/BugTracker#3]
Neither DOTA_DEFAULT_UI_ACTION_MINIMAP nor DOTA_DEFAULT_UI_ACTION_PANEL do not hide the radar button.

**Comment by SinZ163** [comment]
Radar being native panorama makes this very annoying to mess with.
Panorama cannot be overridden via addons (custom gamemodes) which makes it even more annoying to mess with (not that it would do anything, its loaded at launch and precached)

**Comment by DoctorGester** [comment]
The thing with that issue is that it actually worked for quite some time and was broken in one of the updates.

**Comment by K1llMan** [comment]
What about overriding default radar styles?
