### ISSUE TITLE
MODIFIER_EVENT_ON_ORDER does not include a position

### ISSUE THREAD

**Issue by Wouterz90** [ModDota/BugTracker#36]
This forces everyone who relies on this to use the orderfilter, while it should be an easy fix.

**Comment by SinZ163** [comment]
@DoctorGester would you consider this a bug or feature request.

**Comment by DoctorGester** [comment]
@SinZ163 more like a bug imo

**Comment by Wouterz90** [comment]
new_pos is included now!
