### ISSUE TITLE
Reborn channel bar ignores AbilityTextureName

### ISSUE THREAD

**Issue by SinZ163** [ModDota/BugTracker#41]
The new HUD currently does `raw://resource/flash3/images/spellicons/{{AbilityTextureName | default: AbilityName}}.png` but the channel bar is doing `file://{images}/spellicons/{{AbilityName}}.png` resulting in the HUD working as intended but the channel bar not

Note, the difference between `raw://` and `file://` is irrelevant for this issue, the issue is not using the AbilityTextureName field in the ability definition
 
![](http://i.imgur.com/SoOdO6b.png)

**Comment by gdrewb-valve** [comment]
Is this still happening?  The Dota team thinks it should be fixed.

**Comment by DoctorGester** [comment]
Confirmed, it's fixed.
