### ISSUE TITLE
Minimap generation is broken

### ISSUE THREAD

**Issue by rossengeorgiev** [ModDota/BugTracker#45]
To generate a minimap, we need to use `dota_minimap_create`

### What happens

Creates a file `game/dota_addons/<name>/resource/overview/home_button.txt`, which is not the name of the map.  It is always `home_button`. The values in the file are also invalid. Looks like min/max values.

edit: the name can be also `700_mk`

```
home_button
{
	material materials/overviews/home_button.vmat
	pos_x 0
	pos_y -2147483648
	scale -332306979139188339659867366684098560.000
}
```

In turn, this also generates `home_button.vmat_c` and `home_button_tga_fd4ff569.vtex_c`, which is just a black square.

### Expected result

```
my_dota_map
{
	material materials/overviews/my_dota_map.vmat
	pos_x -3072
	pos_y -176
	scale 6.625
}
```

and correct minimap texture image

Most likely related to #42

**Comment by superdotaplaya** [comment]
when I use this command the whole thing crashes on me

**Comment by salacryl** [comment]
Changing the  values doesn't matter. TGA works fine.

**Comment by DoctorGester** [comment]
yeeeee

Fixed with dark moon update
