### ISSUE TITLE
Add a global castfilter

### ISSUE THREAD

**Issue by Yahnich** [ModDota/BugTracker#47]
As currently some other very useful filters are available as well (damage filter, order filter) it'd be nice if we could access the cast filter as well; would allow more flexibility in making custom disables or making non-mana resources easier without remaking every ability into a lua ability.

**Comment by SinZ163** [comment]
can't a castfilter be done with an order filter?

**Comment by Arhowk** [comment]
^ correct a cast is just a type of order, i don't really know what this issue is about

**Comment by DoctorGester** [comment]
@SinZ order filter triggers on order. Meaning queued orders trigger immediately too. It's not suitable for any real logic, only cosmetic filtering like formations or complete filtering like glyph denial.

**Comment by Yahnich** [comment]
an alternate solution to this would be that the order filter only triggers when the order is actually happening instead of when it is queued

**Comment by Yahnich** [comment]
after experimentation it appears the order filter now properly triggers only when the order executes (at least for cast orders i havent checked others)

**Comment by DoctorGester** [comment]
Queued orders now also retrigger when the actual order happens with queue = 0 parameter. Awesome.
