### ISSUE TITLE
Point_worldtext entity is bugged and viewing it in Hammer causes an immediate CTD

### ISSUE THREAD

**Issue by Toyoka** [ModDota/BugTracker#48]
After some back-and-forth troubleshooting on the #dota2mods IRC, VicFrank and I have come to the conclusion that viewing a point_worldtext entity in a viewport (both 3d and 2d) in Hammer causes an immediate CTD. No special interactions are required (this is a confirmed issue). Simply placing and seeing the point_worldtext entity causes this crash.

x-referencing from dev forum: http://dev.dota2.com/showthread.php?t=275335&p=1413539#post1413539

**Comment by Toyoka** [comment]
Update: The newly added **point_clientui_world_text_panel** also causes an instant crash when placed in Hammer.

**Comment by gdrewb-valve** [comment]
Is this still happening?  A fix went out in a recent update.

**Comment by DoctorGester** [comment]
@gdrewb-valve still happening for me for both point_clientui_world_text_panel and point_worldtext

Crash dump attached.

Steps to reproduce:
1. Open hammer
2. Create new map
3. Place a new entity of a chosen type
 
[dota2_2017_0210_065602_0_accessviolation.zip](https://github.com/ModDota/BugTracker/files/765642/dota2_2017_0210_065602_0_accessviolation.zip)

**Comment by gdrewb-valve** [comment]
Oops, the fix has been made but not shipped yet, sorry for the misinformation.  I'll update again when it really does ship.

**Comment by Toyoka** [comment]
Thanks Drew!

**Comment by DoctorGester** [comment]
Seems fixed
