### ISSUE TITLE
dota_item_rune_spawner doesn't spawn any runes

### ISSUE THREAD

**Issue by rossengeorgiev** [ModDota/BugTracker#49]
All maps prior 7.00 can't have runes at the moment, unless they use custom code. `dota_item_rune_spawner` simply does nothing.

7.00 map uses different entities, so it would be great if `dota_item_rune_spawner` could retain the original behavior of spawning a rune at 0:00 and then every 2 minutes. For compatibility.

**Comment by darklordabc** [comment]
This has been fixed in recent update. With one caveat: Spawners that normally don't spawn, like the river ones at the 0:00 mark, will still spawn bounty runes, so it ends up with being much more bounty runes, besides that, everything works.

**Comment by DoctorGester** [comment]
fixed with defects, see #70
