### ISSUE TITLE
Entities.GetOwnerPlayer/Entities.IsOwnedByPlayer method is missing

### ISSUE THREAD

**Issue by DoctorGester** [ModDota/BugTracker#59]
As the title states. This is a crucial method with no proper replacement. IsControllableByPlayer is close, but it fails in case of disconnects and many other cases.

**Comment by gdrewb-valve** [comment]
Entities.GetPlayerOwnerID was added in the latest update, is that closer to what you want?

**Comment by DoctorGester** [comment]
@gdrewb-valve exactly what's I was looking for, however it returns -1 in all cases I've tested so far, using it like this: Entities.GetPlayerOwnerID(entity.id) (it's a 100% valid entity id)

**Comment by DoctorGester** [comment]
I tested it more and it only returns a correct player id for a main player hero.
Any unit-heroes or controllable units or whatever return -1.

**Comment by gdrewb-valve** [comment]
I think it's the same underlying routine exposed to Lua.  I'll check around if there's something better.

**Comment by DoctorGester** [comment]
Looks like it. I am actually not sure if all of that is supposed to happen, GetOwner, GetOwnerEntity, GetPlayerOwner all return nil for my units in Lua, just like GetPlayerID and GetOwnerPlayerID return -1 for them, and I've never used these functions before so I don't actually know if that's okay.

I went into a separate gamemode, subscribed to npc spawn, picked lycan and spawned his wolves, their owners/owner players printed out fine. So that may be a problem with my code.

**Comment by DoctorGester** [comment]
Okay, function is working as intended after explicitly doing SetPlayerID on a newly spawned unit. To why is this required and when is that ever needed (except this case) and whom do I pray to so GetPlayerOwner returned something is a whole another issue.

Thanks!
