### ISSUE TITLE
When a hero has no talents, Dota crashes when mouse hovering over talent UI

### ISSUE THREAD

**Issue by SinZ163** [ModDota/BugTracker#61]
Fairly straight forward, new bug as of Jan 20/Jan 21st update

**Comment by darklordabc** [comment]
I think this is fixed, can anyone else confirm?

**Comment by darklordabc** [comment]
![image](https://cloud.githubusercontent.com/assets/16277198/22911819/eab41ce0-f2b5-11e6-892a-2e039627cde2.png)
This has been fixed, please close this issue.

**Comment by DoctorGester** [comment]
Nice, thanks for confirming.
