### ISSUE TITLE
Fog of War only works on the first 64x64 portion of the map

### ISSUE THREAD

**Issue by ChalkyBrush** [ModDota/BugTracker#66]
Fog of war beyond the bottom left 64x64 can not be revealed by any means

**Comment by Dreoh** [comment]
This has made my map ReIncarnation Beta unplayable

**Comment by rossengeorgiev** [comment]
Can confirm bug, see below. Also FOW doesn't show on minimap. 

![broken_fog](https://cloud.githubusercontent.com/assets/2720787/22407523/e85842a8-e65f-11e6-82fc-405ec5b96a7c.png)

128x128 grid

**Comment by DoctorGester** [comment]
Fixed
