### ISSUE TITLE
Selecting an existing world_bounds entity will not show min/max whiskers

### ISSUE THREAD

**Issue by rossengeorgiev** [ModDota/BugTracker#68]
They show when you create a brand new one. See below. Probably related to #66

![world_bounds_entity_bug](https://cloud.githubusercontent.com/assets/2720787/22407540/522c9152-e660-11e6-93c6-310ef20d3049.png)

**Comment by gdrewb-valve** [comment]
#66 was fixed, is this still happening?

**Comment by rossengeorgiev** [comment]
@gdrewb-valve checking now

**Comment by rossengeorgiev** [comment]
@gdrewb-valve Negative, still not working

![a](https://cloud.githubusercontent.com/assets/2720787/22813619/f510cf40-ef44-11e6-8090-3ab1f8205402.png)

**Comment by gdrewb-valve** [comment]
A dev here tried to repro but wasn't able to, is there a simple way for them to try what you're doing?

**Comment by rossengeorgiev** [comment]
Open existing map, select world_bounds entity. 

Or create world_bounds (it will have whiskers), deselect and select again.

**Comment by gdrewb-valve** [comment]
They say they still can't get it to happen so it's unclear what's going on.  Thanks for retrying.

**Comment by Toyoka** [comment]
Not an issue. This happens when "Show helpers" is turned off in Hammer.

https://streamable.com/wfk8h

Move along!

**Comment by DoctorGester** [comment]
OP won't ever live this down

**Comment by rossengeorgiev** [comment]
@gdrewb-valve my bad, thanks for looking into this
