### ISSUE TITLE
Crash on disconnecting from a custom game

### ISSUE THREAD

**Issue by DoctorGester** [ModDota/BugTracker#69]
So far tested on Overthrow and Crumbling Island Arena by multiple people.

Steps to reproduce:

1. Create/start a custom lobby.
2. Wait until it fully loads.
3. Disconnect/leave the game.
4. Start another lobby (same settings), wait till the game loads.
5. Pressing disconnect crashes the game.

Crash dump: [dota2_2016_0301_180736_0_accessviolation.zip](https://github.com/ModDota/BugTracker/files/745124/dota2_2016_0301_180736_0_accessviolation.zip)

**Comment by Perryvw** [comment]
Fixed
