### ISSUE TITLE
Tools crashing after restarting custom game multiple times

### ISSUE THREAD

**Issue by Perryvw** [ModDota/BugTracker#71]
Like the title says, after running a custom game 3-5 times the tools crash. Happens when launching with `dota_launch_custom_game` and also when restarting with `restart`, both after around 3 times.

Confirmed by multiple other developers.

This is possibly connected to #69 

GitHub did not accept the zip with dump so I uploaded it to my puush: https://puu.sh/tLxt5/578566fa95.zip

**Comment by Arhowk** [comment]
Retracted: I experimented with this some more and am encountering the same issue.

**Comment by Dreoh** [comment]
Can confirm it is happening to me

**Comment by SinZ163** [comment]
It was happening in my custom game which has not much going on

**Comment by darklordabc** [comment]
++

**Comment by Perryvw** [comment]
Fixed
