### ISSUE TITLE
cl_panorama_script_help doesn't dump important C API bindings

### ISSUE THREAD

**Issue by Arhowk** [ModDota/BugTracker#72]
The current version of cl_panorama_script_help basically prints out all of the JS-exposed functions available to certain panels and some predefined variables but it doesn't automatically define some important things.

These include, but are not limited to-

DOTAItemImage - "itemname" and "contententityindex" are both required for this panel to behave properly, neither are exposed with the command. (The two parameters are only known because of the "ui_example" folder given to us quite some time ago)
DOTAShopItem - Some parameters are required to specify which item the panel has but it is unknown since no example has been given
DOTAScenePanel - There are a great deal of parameters such as "camera" and "particlesonly" that are only known because they are used in random places scattered throughout the game UI

**Comment by DoctorGester** [comment]
DOTAScenePanel things like camera, particleonly, unit and many other parameters are XML-only, so it's okay that they are not printed. Pretty sure same happens to ShopItem thingy too.

**Comment by Arhowk** [comment]
> DOTAScenePanel things like camera, particleonly, unit and many other parameters are XML-only, so it's okay that they are not printed

It's okay that they arent included in the JS dump because they arent JS properties but it would still be nice to know them, nevertheless. In addition most scene panels are static when used in dota whereas all of the instances of DOTAShopItem are dynamic, meaning that it's either done using a property like DOTAItemImage or in C++ which would make me a sad panda.

**Comment by SinZ163** [comment]
@Arhowk The command only dumps things that have been accessed by javascript before the command has been executed. it will see DOTAItemImage's stuff if you run it at the correct time, but the other two are beyond the scope of `cl_panorama_script_help` as its not exposed to script.

The real request is expose access to the Debug fields to javascript, which will see *some* of the interesting fields on scenepanel, shopitem(?) and others.
