### ISSUE TITLE
Bug with SetMaxHealth reverting on animation

### ISSUE THREAD

**Issue by dustingraham** [ModDota/BugTracker#77]
I'm using barebones, so maybe there's something else here. Can anyone else test and verify this happens for them? I noticed it when I was triggering an animation on the unit. But, it appears to happen any time the unit makes an animation, and I think the ember's chains' root triggers an animation which triggers this bug.

npc_heroes_custom.txt

```
"DOTAHeroes"
{
  "npc_dota_hero_luna"
  {
    "StatusHealth"        "5000"
  }
}
```

lua

```
  local test = CreateUnitByName("npc_dota_hero_luna", hero:GetAbsOrigin(), true, nil, nil, DOTA_TEAM_NEUTRALS)
  test:SetBaseMaxHealth(3000)
  test:SetMaxHealth(2000)
  test:SetHealth(1000)
```
    
Steps
1. Pick Ember
2. Spawn Enemy
- Observe health 1000 out of 2000
3. Train Searing Chains
4. Cast Searing Chains so that it hits luna.
- Observe health changes to 1709/5300 **!BUG!**

**Comment by Arhowk** [comment]
I was able to reproduce this

However, regardless, this is a scenario that should not occur in a normal game. SetBaseMaxHealth should never be used on heroes because it blocks stat recalculations. If you want to modify this you should use a modifier instead.

**Comment by dustingraham** [comment]
I don't mind not using SetBaseMaxHealth, I was just using SetMaxHealth and SetHealth, which worked for me. Someone suggested including SetBaseMaxHealth, so I threw it in there as a parameter.

I'd like to scale the HP based on variables, so I can't use static values in the txt file.

**Comment by Perryvw** [comment]
Sounds like lua modifiers would be the way to go here. Setting basemaxhealth and regular maxhealth (to different values) seems pretty dodgy. I will mark this as a bug regardless.

**Comment by dustingraham** [comment]
I'm fine with closing this. After spending several hours yesterday and more hours today, I agree that SetHealth and SetMaxHealth are low level functions that shouldn't be used. Modifiers are the way to go.

I do think it's a bug though since heroes inherit from entity class.

SetBaseMaxHealth and SetHealth can be omitted from this bug, it has a problem regardless with just the SetMaxHealth call. The other two were just to include possibilities and context that I thought were useful at the time.

Thanks for the support.

**Comment by DoctorGester** [comment]
Not a bug
