### ISSUE TITLE
Inline HTML only supports single quotes

### ISSUE THREAD

**Issue by SinZ163** [ModDota/BugTracker#78]
This is common in html enabled localization, having something like
```html
"key" "This is a <font color="#ff0000">test</font>!"
```
will result in only displaying "This is a !" after localization, where-as 
```html
"key" "This is a <font color='#ff0000'>test</font>!"
```
will work as intended

**Comment by Arhowk** [comment]
did you try escaping the double quotes

(For what it's worth this seems like intended behavior as you shouldn't have unescaped double quotes in a double quote-enclosed string anyway)

**Comment by SinZ163** [comment]
Thanks for the straight response
