### ISSUE TITLE
The targeting chalk outline doesn't update after changing camera settings

### ISSUE THREAD

**Issue by Arhowk** [ModDota/BugTracker#96]
I'll get a video of this momentarily but the jist of the bug is this: If you have your cursor hovered over some entity that produces the green chalk outline [(visible on the viper)](http://i.imgur.com/ImGqkXv.png) and change the camera settings (SetCameraTarget, SetCameraPitch, etc.) the outline will be stuck for about 5 seconds

**Comment by Arhowk** [comment]
This isn't a feature request it's a "General" "Bug"

Video- https://www.youtube.com/watch?v=Wq5FDHwurYk&feature=youtu.be

**Comment by Arhowk** [comment]
This was resolved in the Juggernaut Arcana update

**Comment by darklordabc** [comment]
Shouldn't you close it then?

**Comment by DoctorGester** [comment]
Closed due to author's incapability to do so.

**Comment by Arhowk** [comment]
Yes, I don't have the admin privileges to close issues.
