### ISSUE TITLE
February 17th update broke "onmouseover" under hidden panels

### ISSUE THREAD

**Issue by Arhowk** [ModDota/BugTracker#98]
Previously I had hidden my game panels through an "opacity: 0" class so they transitioned properly. With the newest update, it appears that all panels below a 0-opacity panel no longer fire "onmouseover" and "onmouseout" events properly. They still fire "onactivate" fine though (haven't checked the other events such as "oncontextmenu")

E/ this is definitely confirmed- I added this line of code to the JS of the opacity: 0 panel and my tooltips work fine now

	$.GetContextPanel().style.position = "5000px 0px 0px";

**Comment by dustingraham** [comment]
Can you try 

`$.GetContextPanel().style.pointerEvents = "none";`

Edit: Bummer that it doesn't work. I threw this pen together to demonstrate how it usually works on the web: http://codepen.io/anon/pen/qRGVeR when you toggle pointer events, it allows the hover to fire on the bottom element. ;)

**Comment by Arhowk** [comment]
[ W PanoramaScript   ]: !! (s2r://panorama/scripts/custom_game/hero_select_new/root.vjs_c, line:7, col:41) - Property setter for CPanelStyle called with invalid css property name (pointerEvents)

**Comment by Perryvw** [comment]
You could also just explicitly set hittest to false on panels you hide.

**Comment by Arhowk** [comment]
After further review, this is standard web behavior so I don't believe it to be a bug but rather a fix to an older bug
