### ISSUE TITLE
"DisableWearables" "1" breaks certain particle attachments after Winter Treasure II update

### ISSUE THREAD

**Issue by DoctorGester** [ModDota/BugTracker#99]
Steps to reproduce:

1. override npc_dota_hero_skeleton_king
2. Add "DisableWearables" "1"
3. ParticleManager:CreateParticle("particles/units/heroes/hero_skeletonking/wraith_king_ambient.vpcf", PATTACH_ABSORIGIN_FOLLOW, hero)

The particle is between his legs. Same happens with phoenix ambient particles, andtimage TI bashers particles etc.

**Comment by Arhowk** [comment]
Just to confirm- these particle attachments work fine if the DisableWearables 1 isn't included (and these particles aren't originally present on the hero), correct?

**Comment by DoctorGester** [comment]
Yes.

Same code routine:

1. Default wearables enabled (see how bashers overlay with default weapons)
![](http://dg-lab.com/mehav)

2. Default wearables disabled (see basher particles around his origin)
![](http://dg-lab.com/dylor)

**Comment by dustingraham** [comment]
This shows the same problem for the default fountain modifier particle on dragon knight.

Normal with wearables.
https://gfycat.com/DeliriousKindheartedChipmunk

Broken without wearables.
https://gfycat.com/CluelessCreamyCaimanlizard

**Comment by DoctorGester** [comment]
One of my players managed to replicate this in demo mode. Works on illusions:

![](https://pp.vk.me/c626525/v626525260/58aab/GTtmkbgIsSQ.jpg)

![](https://pp.vk.me/c626525/v626525260/58ab2/r-f2DZTo8XA.jpg)

**Comment by DoctorGester** [comment]
Fixed
